### PR TITLE
Cleanup, formatting, outdated information, etc.

### PR DESCRIPTION
**Pull request by hensleyrob**
* Updated build agent -> build pipeline information.
* Add missing information about referenced DLL's.
* Dynamics AX -> Dynamics 365.
* Various cleanup and formatting.

### CODE REVIEW

**Comment by MargoC** [comment]
Thanks @hensleyrob. Given that you commented on a number of topics, it's going to take us a while to get them assigned to the appropriate folks. We'll have PMs take a look at your suggestions, and get back to you.

**Comment by hensleyrob** [comment]
@MargoC in the future would you rather a separate PR per page?

**Comment by MargoC** [comment]
@hensleyrob , Yes, separate requests make it easier for us to run through your changes quickly. Having them all in one pull request makes us hold all of your changes until they have all been approved. :-)

**Comment by ChrisGarty** [comment]
Thanks for the contributions Rob!! We'd love more change requests like this :)
Now if you could just change your profile picture to a photo of you, I'd be able to put a face to the name! ;)

**Comment by MargoC** [comment]
Hi Rob, 

Your changes are live--thanks so much for the contribution! However, I'm going to close your pull request without merging it, because we took long enough to merge it that I had to move the changes over manually.

**Pull request closed without merging**
