### PR TITLE
Update prepayments-invoices-vs-prepayments.md

### PR DESCRIPTION
**Pull request by vavd**

### CODE REVIEW

**Comment by tonyafehr** [comment]
We are not going to include the requested link.

**Comment by vavd** [comment]
Hello @tonyafehr,
Thank you for the response.
Anything wrong with the article?
This article should help to get more info about the functionality.
The similar links were included in the docs before.
For example [here](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/924).

**Comment by tonyafehr** [comment]
It’s not a best practice for us to link an external site from our documentation. Also, the link is for AX 2012 and includes screenshots that do not show our current product. As a result, I conferred with the author of this topic and we agreed not to include the link provided. If you believe that the topic in question requires additional information, please note that in Docs feedback for this topic, and we will consider updating the topic as requested.

**Comment by vavd** [comment]
Thank you @tonyafehr, your feedback is really appreciated.

**Pull request closed without merging**
