### PR TITLE
Update versions-update-policy.md : 7.2 support

### PR DESCRIPTION
**Pull request by damienmaspero**
Those customers who submitted extensibility requests by January 1, 2019, will be supported on version 7.3 and version 7.2 until their extensibility requests are fulfilled.
Reasoning : You cannot upgrade from 7.2 to 7.3 in parallel of upgrading from 7.2 to 8.x

### CODE REVIEW

**Comment by tonyafehr** [comment]
@ryanCcarlson, can you review this to be sure that it's accurate. Thanks!

**Comment by RyanCCarlson2** [comment]
I've not heard any ask for 7.2 to remain active as well.  This is new information. @damienmaspero where is this ask from?

**Comment by damienmaspero** [comment]
NHS Professionals asked for it as they are currently upgrading from 7.2 to 8.x/waiting for extensions from Microsoft. @ClaudiaBetz-Haubold also had such a request if I understood correctly.

**Comment by tonyafehr** [comment]
@meeramahabala, @josaw1, or @ShellyBakke, please review this request to be sure that it's accurate.

**Pull request closed without merging**
