### PR TITLE
Update configure-export-data-lake.md

### PR DESCRIPTION
**Pull request by Simon-Syd**
I just write the step by step, because the display on Azure portal has changed : 
1. In **Azure portal**, open the key vault that you created earlier.
2. In **Settings**, select **Access configuration**.
3. Then **go to access policies** and **create** to create a new policy.
4. In the **Secret permissions** fields, select **Get** and **List**.
5. In the **Select principal** field, locate and select the application, **Microsoft Dynamics ERP Microservices**, and then click **Select**. 

    > [!NOTE]
    > If you can't find **Microsoft Dynamics ERP Microservices**, see the [Create Service Principal](#createServicePrincipal) section in this document.
6. Select **Save**

    You should see application with access to your key vault as shown below.

    | Application                          | Secret permissions |
    |--------------------------------------|--------------------|
    | Microsoft Dynamics ERP Microservices | Get, List          |

### CODE REVIEW

**Comment by buck1ey** [comment]
### :white_check_mark: Organization membership check passed
_Requester is not a member of the MicrosoftDocs organization._

**Comment by johnmichalak** [comment]
Reached out to the author on 1/12/23 to see if these changes can be merged.

**Comment by MilindaV2** [comment]
revised steps above are correct. Suggest merging with proposed changes

**Comment by Simon-Syd** [comment]
good evening @MilindaV2 & @johnmichalak 

sorry it was the first time I edited the doc .... and I made mistake !
because now in the link : 
https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake#authorize

you can find this text "this part is not in the right order"
and I wrote from step 1 to 6, and it replace the steps 7 to 13, so it have to be removed !
now I can understand that I should do this when I write my modification ?

sorry for the confusion and thanks for your feedback !

**Pull request merged**
