### PR TITLE
add documentation for new 10.0.24 VHD

### PR DESCRIPTION
**Pull request by FH-Inway**

### CODE REVIEW

**Comment by buck1ey** [comment]
### :white_check_mark: Organization membership check passed
_Requester is not a member of the MicrosoftDocs organization._

**Comment by FH-Inway** [comment]
@josaw1 Could you let me know why this change is not considered? I think it adds valuable information about the new VHD setup.

**Comment by sericks007** [comment]
@FH-Inway, please see [Set up the downloadable VHD for first use](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/vhd-setup).

**Comment by FH-Inway** [comment]
@sericks007 Thanks for the response. I'm aware of [Set up the downloadable VHD for first use](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/vhd-setup). Actually, it is the reason for the proposed change. The goal is to raise awareness of this new guide for the 10.0.24 VHD by linking to it in a note on this page (which contains the general documentation on environments, including local VHD environments). If someone just follows this documentation, they encounter the error that is described in the Q&A I added at the end. Both the note and the Q&A link to the new guide, which helps people discover it. This also helps avoiding support cases for Microsoft and partners from people setting up the 10.0.24 VHD for the first time.
Please consider the proposed changes for review or let me know how visibility of the new guide could be improved otherwise.

**Comment by FH-Inway** [comment]
@sericks007 I was wondering when the changes to this page will be available on docs.microsoft.com? I saw that other changes made at a later date are already published, e.g. https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/commit/964cbeb2d79bd00dd60ee34bc970ab0700b6211c

**Comment by sericks007** [comment]
Thanks for the reminder, @FH-Inway!  It is updated now.

**Pull request merged**
