### PR TITLE
Gboyko/talent recurring export tutorial

### PR DESCRIPTION
**Pull request by gregboyko**
This is a brand new article for Talent Core HR that provides a tutorial on how to do recurring data export from Core HR using an Azure Logic App.

This is the first time I'm creating a brand new article, so please review carefully and let me know if I've missed anything.

### CODE REVIEW

**Comment by gregboyko** [comment]
@jcart1106 I'd appreciate your review on this article.

**Comment by jcart1106** [comment]
We've got one link to Azure Logic Apps in the topic. It would be great it if we could link to each type of function or step that we are using. Also, linking to the overall DMF topic from FinOps would be helpful too.

**Comment by tonyafehr** [comment]
The Content Publishing team will edit this topic before it's published.

**Comment by gregboyko** [comment]
> We've got one link to Azure Logic Apps in the topic. It would be great it if we could link to each type of function or step that we are using. Also, linking to the overall DMF topic from FinOps would be helpful too.

Thanks @jcart1106. I've added several additional links to the connectors/technologies used.

**Comment by gregboyko** [comment]
> The Content Publishing team will edit this topic before it's published.

Thanks @tonyafehr. This is the first time I'm going through the full flow for publishing a new topic, so any help and suggestions are appreciated!

**Pull request merged**
